# Generated by Django 3.2 on 2021-06-26 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartParking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('s_id', models.IntegerField()),
            ],
        ),

    ]
