# Generated by Django 3.2 on 2021-06-27 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartParking', '0002_driver_reserves_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_id', models.IntegerField()),
                ('plate_no', models.CharField(max_length=10)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartParking.driver')),
                ('slots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartParking.slots')),
            ],
        ),
    ]
