# Generated by Django 3.2 on 2021-07-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartParking', '0003_reserves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
