# Generated by Django 3.2 on 2021-07-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartParking', '0004_alter_driver_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
    ]
